from typing import Any, Protocol


class GraphRuntimeBackend(Protocol):
    async def search_nodes(
        self, query: str, label: str | None = None, limit: int = 20
    ) -> list[dict]: ...

    async def expand_neighbors(
        self, node_id: str, depth: int = 1, limit: int = 20
    ) -> dict[str, Any]: ...

    async def get_node(self, node_id: str) -> dict[str, Any] | None: ...

    async def find_path(self, from_name: str, to_name: str, max_depth: int = 4) -> list[dict]: ...

    async def execute_readonly_cypher(self, query: str) -> list[dict[str, Any]]: ...

    async def get_schema_summary(self) -> dict[str, Any]: ...
